# Generated by Django 4.2 on 2024-02-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text="The object's creation date/time", null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now_add=True, help_text="The object's last update date/time", null=True, verbose_name='updated on')),
                ('mail', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('response_trace', models.TextField(blank=True, null=True)),
                ('response_code', models.CharField(blank=True, max_length=255, null=True)),
                ('response_message', models.CharField(blank=True, max_length=255, null=True)),
                ('response_status', models.CharField(blank=True, max_length=255, null=True)),
                ('response_error', models.TextField(blank=True, null=True)),
                ('response_error_trace', models.TextField(blank=True, null=True)),
                ('response_error_code', models.CharField(blank=True, max_length=255, null=True)),
                ('response_error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('response_error_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-updated_on'],
                'get_latest_by': 'updated_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unsuscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text="The object's creation date/time", null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now_add=True, help_text="The object's last update date/time", null=True, verbose_name='updated on')),
                ('mail', models.EmailField(blank=True, max_length=255, null=True)),
                ('email_key', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ['-updated_on'],
                'get_latest_by': 'updated_on',
                'abstract': False,
            },
        ),
    ]
