# Generated by Django 4.2 on 2024-02-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='interface',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'DEFAULT'), ('FORGET_PASSWORD', 'FORGET_PASSWORD'), ('WELCOME', 'WELCOME'), ('VERIFY_EMAIL', 'VERIFY_EMAIL')], max_length=255, null=True, unique=True),
        ),
    ]
