# Generated by Django 4.2 on 2024-02-18 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text="The object's creation date/time", null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now_add=True, help_text="The object's last update date/time", null=True, verbose_name='updated on')),
                ('interface', models.CharField(blank=True, choices=[], max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('html_src', models.FileField(blank=True, null=True, upload_to='mails/')),
            ],
            options={
                'ordering': ['-updated_on'],
                'get_latest_by': 'updated_on',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='body',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='error',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='error_trace',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='response',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='response_error',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='response_error_code',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='response_error_message',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='response_error_status',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='response_error_trace',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='response_message',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='response_status',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='response_trace',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mailsended',
            name='subject',
        ),
        migrations.AddField(
            model_name='mailsended',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='mailsended',
            name='to',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailsended',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailling.mail'),
        ),
    ]
