# Generated by Django 4.2 on 2024-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0003_mailsended_created_at_mailtemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='interface',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True, unique=True),
        ),
    ]
