# Generated by Django 4.2 on 2024-02-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0003_mail_remove_mailsended_body_remove_mailsended_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsended',
            name='error',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
