# Generated by Django 4.2 on 2024-02-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0004_mailsended_error'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mail',
            new_name='MailTemplate',
        ),
    ]
