# Generated by Django 4.2 on 2024-02-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0004_alter_mailtemplate_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='interface',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'DEFAULT'), ('FORGET_PASSWORD', 'FORGET_PASSWORD'), ('WELCOME', 'WELCOME')], max_length=255, null=True, unique=True),
        ),
    ]
