# Generated by Django 4.2 on 2024-02-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0007_rename_mail_mailsended_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text="The object's creation date/time", null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now_add=True, help_text="The object's last update date/time", null=True, verbose_name='updated on')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_text', models.TextField(blank=True, null=True)),
                ('html_src', models.FileField(blank=True, null=True, upload_to='mails/')),
            ],
            options={
                'ordering': ['-updated_on'],
                'get_latest_by': 'updated_on',
                'abstract': False,
            },
        ),
    ]
