# Generated by Django 4.2 on 2024-02-18 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0008_mailtemplatetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplatetranslation',
            name='translateObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translates', to='mailling.mailtemplate'),
        ),
    ]
